# Generated by Django 5.1.4 on 2026-07-08 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_processo', models.CharField(blank=True, max_length=100)),
                ('cod_car', models.CharField(blank=True, max_length=100)),
                ('requerimento', models.CharField(blank=True, max_length=255)),
                ('nome_requerente', models.CharField(blank=True, max_length=255)),
                ('ato_administrativo', models.CharField(blank=True, max_length=255)),
                ('atividade', models.CharField(default='Pecuária', max_length=255)),
                ('porte', models.CharField(blank=True, choices=[('Pequeno', 'Pequeno'), ('Médio', 'Médio'), ('Grande', 'Grande')], max_length=20)),
                ('area_propriedade', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('area_atividade', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('municipio', models.CharField(blank=True, max_length=150)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('data_chegada', models.DateField(blank=True, null=True)),
                ('opc_doc', models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Nao', 'Não'), ('NA', 'Não se aplica')], max_length=3)),
                ('opc_car', models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Nao', 'Não'), ('NA', 'Não se aplica')], max_length=3)),
                ('opc_art', models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Nao', 'Não'), ('NA', 'Não se aplica')], max_length=3)),
                ('opc_agua', models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Nao', 'Não'), ('NA', 'Não se aplica')], max_length=3)),
                ('opc_apoio', models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Nao', 'Não'), ('NA', 'Não se aplica')], max_length=3)),
                ('opc_spr', models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Nao', 'Não'), ('NA', 'Não se aplica')], max_length=3)),
                ('opc_infr', models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Nao', 'Não'), ('NA', 'Não se aplica')], max_length=3)),
                ('opc_resi', models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Nao', 'Não'), ('NA', 'Não se aplica')], max_length=3)),
                ('opc_cons', models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Nao', 'Não'), ('NA', 'Não se aplica')], max_length=3)),
                ('opc_ana', models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Nao', 'Não'), ('NA', 'Não se aplica')], max_length=3)),
                ('observacao', models.TextField(blank=True)),
                ('condicionante', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('EM_TRAMITE', 'Em trâmite'), ('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado')], default='RASCUNHO', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processos_criados', to=settings.AUTH_USER_MODEL)),
                ('responsavel_atual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processos_na_fila', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tramitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField(blank=True)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('de_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tramitacoes_enviadas', to=settings.AUTH_USER_MODEL)),
                ('para_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tramitacoes_recebidas', to=settings.AUTH_USER_MODEL)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramitacoes', to='pareceres.processo')),
            ],
            options={
                'ordering': ['data_hora'],
            },
        ),
    ]
