# Generated by Django 5.1.4 on 2026-07-08 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pareceres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='agua_justificativa',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='processo',
            name='agua_tipo',
            field=models.CharField(blank=True, choices=[('DUI', 'DUI'), ('Outorga', 'Outorga')], max_length=20),
        ),
        migrations.AddField(
            model_name='processo',
            name='apoio_justificativa',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='processo',
            name='apoio_tipo',
            field=models.CharField(blank=True, choices=[('DUI', 'DUI'), ('Outorga', 'Outorga')], max_length=20),
        ),
        migrations.AddField(
            model_name='processo',
            name='art_justificativa',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='processo',
            name='car_situacao',
            field=models.CharField(blank=True, choices=[('Deficit', 'Déficit de Reserva Legal'), ('Conflito', 'CAR em Conflito')], max_length=20),
        ),
        migrations.AddField(
            model_name='processo',
            name='spr_ard',
            field=models.TextField(blank=True),
        ),
    ]
