# Generated by Django 5.1.4 on 2026-07-08 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pareceres', '0002_processo_agua_justificativa_processo_agua_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='classificacoes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='processo',
            name='atividade',
            field=models.CharField(choices=[('Silvicultura', 'Silvicultura'), ('Agricultura', 'Agricultura'), ('Pecuária', 'Pecuária'), ('Suinocultura', 'Suinocultura')], default='Pecuária', max_length=20),
        ),
    ]
